### PR TITLE
Improve CH376 emulation + add CREATE_DIR & ERASE_FILE support for Linux

### PR DESCRIPTION
**Pull request by assinie**
Note: new system_directory_delete() function tested on Linux OS only

### CODE REVIEW

**Comment by jedeoric** [comment]
Assinie and me are checking emulation on real hardware before accepting this merge.

**Comment by pete-gordon** [comment]
ok cool. I figure you're the expert :-)

**Comment by iss000** [comment]
I've checked and everything looks ok. At least Linux compilation now works again :).

**Comment by jedeoric** [comment]
We finished all tests, @assinie is correcting the code

**Comment by jedeoric** [comment]
Windows version is working (crashes disappears) There is a fix for this target from assinie

**Comment by jedeoric** [comment]
if everbody is OK, can i merge pull request ? @iss @assinie @pete-gordon 

Tests are OK, it works under windows & linux :)

**Pull request merged**
