### PR TITLE
Add Lies_mich.txt

### PR DESCRIPTION
**Pull request by bodhi-baum**
German translation of the readme.txt

### CODE REVIEW

**Comment by bodhi-baum** [comment]
@ pete-gordon: I have translated the english readme.txt of version 1.2 into german, because I like the emulator very much and would like to contribute to make it more international. Although I am not very good at programming, I am happy to take on additional tasks regarding documentation and testing if there is interest or need.

**Comment by iss000** [comment]
Das ist prima! ;)

But if I may suggest the file name to be somethink like: ReadMe.DE.txt or ReadMe-DE.txt
IMO it's more consistent with other names an fits better in the directory listing?

**Comment by bodhi-baum** [comment]
You are right. This was my first try here at Github, so I thought the topic would be just visible in a discussion.

**Comment by bodhi-baum** [comment]
@iss000: I gave it a new name and think it now fits better.

**Comment by iss000** [comment]
Closed with #156

**Pull request closed without merging**
