### PR TITLE
Fix MSVC2017 build environment dependencies

### PR DESCRIPTION
**Pull request by rzumer**
The current version of the project refers to absolute paths in a specific user's environment. Without changing the build system, I added `vspkg` as a submodule and replaced `make_links.cmd` with MSBUILD pre- and post-build events, which allows us to automatically fetch `vspkg` and `SDL2` on compilation if they are not already present, and copy all the needed files to the build directory more easily. The readme file is updated accordingly.

I also added a `.gitattributes` file to stop git from trying to convert line endings to LF for Visual Studio projects and solutions.

### CODE REVIEW

**Comment by assinie** [comment]
I'm not sure adding vcpkg as git submodule is a good idea because it's platform specific (MicroSoft Windows and VisualStudio in this case).

**Comment by rzumer** [comment]
I understand that point of view, but submodules are not pulled by default, so on non-MSVC builds there is no need to initialize them, while on MSVC builds the process is fully automated and a lot more straightforward.

**Comment by rzumer** [comment]
@Blonder Were you looking at the first commit? It was fixed in a subsequent one, so looking at the overall PR diff it should be fine.

**Comment by Blonder** [comment]
@rzumer Yes, maybe I was looking at the first one, sorry.

**Comment by assinie** [comment]
@rzumer I understand but when a git repository contains submodules, the first thing to do is usually a `git submodule update --init` (I'm a Linux user, sorry)
.
vcpkg is a library manager, so if someone else used to use another tools do we add them as a new sub-modules?

I don't know if it's feasible but maybe you can modify the vs project to do the `git submodule add ...` if needed?

**Comment by rzumer** [comment]
I replaced it with a clone.

**Comment by Blonder** [comment]
I tested this solution today - it works nicely, but I would move the vcpkg folder into the msvc folder so its clear that it belongs / is necessary for msvc only.

**Comment by rzumer** [comment]
Is this ready to merge or is there an issue remaining?

**Pull request merged**
